### ISSUE TITLE
[Request] A Text log of files it didn't recognize

### ISSUE THREAD

**Issue by blinkydoos** [eklipse2009/ZX-Pokemaster#4]
Could we have an option to save a text log of files it didn't recognize in the database (but were renamed anyway) ?

I made a few of my own z80 snapshots but Pokemaster named them wrong (and a lot of new-ish releases haven't been added yet).

**Comment by blinkydoos** [comment]
How's it going ? :-)

**Comment by eklipse2009** [comment]
Hello!
Sorrry for not replying earlier.
Currently I'm busy with adding missing ZX Spectrum games to TOSEC.
I'll get back to all the issues you posted in a while.

**Comment by eklipse2009** [comment]
I've uploaded the new version on Sourceforge:
https://sourceforge.net/projects/zx-pokemaster/
It now features decent logging instead of "in your face" error messages.
Does this type of logging satisfy your requirements?
Would you like to see any additional information?

**Comment by blinkydoos** [comment]
Thanks, i'll have to check it later as Sourceforge doesn't seem to work lately.

**Comment by eklipse2009** [comment]
@blinkydoos if you have Facebook you may download it from the ZX Pokemaster group:
https://www.facebook.com/groups/zxpokemaster/
The group is open and I've shared the latest beta on it because of the problems on SF.

**Comment by blinkydoos** [comment]
The log is fine, thanks. I'll close this now.
